version: '3'
services:
  kafka:
    image: bitnami/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  productor:
    build:
      context: ./docker/productor/
      dockerfile: ./Dockerfile
    hostname: productor
    container_name: productor
    depends_on:
      - kafka
  anonimizador:
    build:
      context: ./docker/anonimizador/
      dockerfile: ./Dockerfile
    hostname: anonimizador
    container_name: anonimizador
    depends_on:
      - kafka
  consumidor:
    build:
      context: ./docker/consumidor/
      dockerfile: ./Dockerfile
    hostname: consumidor
    container_name: consumidor
    depends_on:
      - kafka
